import java.util.Scanner;

public class RandomNumber{
    public static void guessTheRandomNumber (){
        double a = Math.random()*100 ;             
        int b = (int) Math.floor(a);
        try (Scanner sc = new Scanner (System.in)) {
            System.out.println("You Have to Guess The Number Which is Randomly Generated by the System between 0 to 100:-");
            for (int i = 1; i <= 10; i++){
                    Float c = sc.nextFloat();
                if (c == b) {
                    System.out.println("Congratulation!! Your Guessing is Correct. " + "It tooks you " + i + " attemps.");
                    int s = (100-(5*(i-1)));
                        System.out.println("Your Score is " + s);
                        return;
                } else if (c > b) {
                    System.out.println("Your entered number is greater than randomly generated number!!");
                } else {
                    System.out.println("Your entered number is less than randomly generated number!!");
                }
                if (i == 10 && c != b) {
                    System.out.println("\nYou have reached the MAXIMUM 10 attemps.\n\nThe Number which is randomly generated is " + b + ".");
                }
            }
            System.out.println();
        }
    }
    public static void main (String args[]) {
        guessTheRandomNumber();
    }
}